#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// WordPress requirement
if(file_exists(__DIR__ . '/public/cms/wp-blog-header.php')) {
    /* Wordpress :( */
    $_SERVER['SERVER_PROTOCOL'] = null;
    $_SERVER['REQUEST_METHOD'] = null;
    $_SERVER['HTTP_HOST'] = null;
    require(__DIR__ . '/public/cms/wp-blog-header.php');
} else {
    echo 'WordPress not installed. Was the "johnpbloch/wordpress" package or `public/cms` folder removed?' . PHP_EOL;
    return;
}

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);
